### ISSUE TITLE
join 관련 문제들

### ISSUE THREAD

**Issue by noion0511** [Bob-Friend/bob-friend-server#16]
1. 계정 인증 방법 https://moonong.tistory.com/45
2. 아이디 중복 확인
3. 로그아웃
4. 회원탈퇴
5. 성별 -> 제 3의 성 https://www.sisunnews.co.kr/news/articleView.html?idxno=101047
6. 동의하기 버튼, 선택(마케팅) 관련

**Comment by qww1552** [comment]
4. DELETE /api/user/{userId}  
```
{
"password":"1234"
}
```
